services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: 
   
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: 
      VIRTUAL_HOST: 
      LETSENCRYPT_HOST: 
      LETSENCRYPT_EMAIL: 
      
    
networks:
  default:
    external:
      name: nginx-proxy
volumes:
  db_data:
